# Generated by Django 4.1.4 on 2023-11-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotest',
            name='show',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
