# Generated by Django 4.1.4 on 2023-11-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_autotest_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmit',
            name='verdict',
            field=models.CharField(default='fail', max_length=255),
            preserve_default=False,
        ),
    ]
