# Generated by Django 4.1.4 on 2023-11-30 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_autotest_time_limit_task_test_ordering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmit',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
