# Generated by Django 4.1.4 on 2023-11-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tasksubmit_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='task_ordering',
            field=models.TextField(default=None, null=True),
        ),
    ]
