# Generated by Django 4.1.4 on 2023-11-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contest_task_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotest',
            name='input',
            field=models.TextField(default=''),
        ),
    ]
