# Generated by Django 4.1.4 on 2023-11-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_autotest_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotest',
            name='input',
            field=models.TextField(default='', null=True),
        ),
    ]
